### ISSUE TITLE
mapred.job.tracker wrong hostname

### ISSUE THREAD

**Issue by buryat** [mesos/hadoop#24]
I have the following mapred.job.tracker setting in core-site.xml
![screenshot 2014-06-16 19 38 11](https://cloud.githubusercontent.com/assets/721503/3294832/6d4fd0e0-f5b1-11e3-9caf-fd9da6f8383a.png)
but in stderr I see that mapred.job.tracker somehow got trimmed:
![screenshot 2014-06-16 19 38 02](https://cloud.githubusercontent.com/assets/721503/3294833/6d508b84-f5b1-11e3-8bbd-a15535ef5fab.png)
so tasktrackers try to connect to the wrong host.

hadoop 2.3.0-cdh5.0.2
mesos 0.19.0

**Comment by tarnfeld** [comment]
Closing this for now, feel free to re-open if this is still a problem.
