### ISSUE TITLE
Deploy CDH5.0.2 tarball with MRv1

### ISSUE THREAD

**Issue by wenruij** [mesos/hadoop#25]
Any guide about deploying CDH5.0.2 tarball with MRv1?
My plan is to deploy a pure hadoop(without mesos) first, 
then connect hadoop with mesos
but seams hard to deploy CDH5.0.2 tarball with MRv1, any guide about this?
  Thanks

**Comment by Ambary** [comment]
@theclaymethod 
Figured out the issue. Hadoop was requesting 1024mb memory, and there weren't any slaves that could satisfy. Where is this configured? It doesn't seem to be obeying:

<property>
    <name>mapred.mesos.slot.mem</name>
    <value>128</value>
    <description>
      This is the total memory required for JVM overhead (10% of this value)
      and the heap (-Xmx) of the task. The value is in MiB.
    </description>
  </property>

Can it  figured out the issue？like this  i need your help

2016-04-06 16:19:49,476 INFO org.apache.hadoop.mapred.ResourcePolicy: JobTracker Status
Pending Map Tasks: 3
Pending Reduce Tasks: 1
Running Map Tasks: 0
Running Reduce Tasks: 0
Idle Map Slots: 0
Idle Reduce Slots: 0
Inactive Map Slots: 0 (launched but no hearbeat yet)
Inactive Reduce Slots: 0 (launched but no hearbeat yet)
Needed Map Slots: 3
Needed Reduce Slots: 1
Unhealthy Trackers: 0
2016-04-06 16:19:49,476 INFO org.apache.hadoop.mapred.ResourcePolicy: Declining offer with insufficient resources for a TaskTracker: cpus: offered 2.0 needed at least 1.0
**mem : offered 992.0 needed at least 1024.0**
disk: offered 276363.0 needed at least 1024.0
ports: at least 2 (sufficient)
2016-04-06 16:19:49,476 INFO org.apache.hadoop.mapred.ResourcePolicy: Unable to fully satisfy needed map/reduce slots: 3 map slots 1 reduce slots remaining
