### ISSUE TITLE
Skip extracting hadoop distribution on Task_Tracker creation

### ISSUE THREAD

**Issue by hansbogert** [mesos/hadoop#42]
Is it really necessary to keep extracting the hadoop distribution every time (referenced by `mapred.mesos.executor.uri` )? Spark imo does this somewhat smarter by just referencing (if no URI is given), the current hadoop distribution's path to the (equivalent of) Task_Tracker. This often holds on clusters with shared storage among the nodes. This would really shorten the startup time, or do I have an configuration error that I'm seeing all those extractions? 
Besides the extra job slowdown this incurs, it's also very wasteful disk-space wise.

**Comment by tarnfeld** [comment]
That's a fair point, I think if you were to set `mapred.mesos.executor.directory` to a path on the slave where Hadoop is installed things should work. You will however run into [this](https://github.com/mesos/hadoop/blob/master/src/main/java/org/apache/hadoop/mapred/ResourcePolicy.java#L390-L394) exception if you don't specify a URI.

I would suggest first setting the directory option and checking that hadoop is being launched from the correct place and if that works, perhaps you could open a PR to allow the executor URI value to be null.
