### ISSUE TITLE
Support for the new ContainerInfo (and Mesos<>Docker)

### ISSUE THREAD

**Issue by tarnfeld** [mesos/hadoop#49]
Currently the Hadoop on Mesos framework only supports the old-style container info protos (used for the External Containerizer). We should also add support for docker container info.

**Comment by andrewrjones** [comment]
Would also like to see this. It doesn't look like Mesos supports the old way of defining containers any more.

**Comment by tarnfeld** [comment]
Ah yes we'll get to this! Maybe I'll work on it in the upcoming #MesosCon hackathon.

**Comment by andrewrjones** [comment]
Great, thanks Tom!

If you do get a chance to work on it then we should have some time to test it next week.

I had been looking through the code recently and it might not just be the [Containerinfo](https://github.com/mesos/hadoop/blob/master/src/main/java/org/apache/hadoop/mapred/ResourcePolicy.java#L296) code that needs to be updated. For example, `mapred.local.dir` is currently [hard coded](https://github.com/mesos/hadoop/blob/master/src/main/java/org/apache/hadoop/mapred/MesosExecutor.java#L187) to `System.getenv("MESOS_DIRECTORY") + "/mapred"`, but this doesn't make sense if we are running inside Docker, so it should at least be configurable.

I'm not sure if there are any other places in the code that make the assumption we are using a Mesos container, but thought I would mention this one in case you wasn't already aware.

**Comment by tarnfeld** [comment]
I've opened #68 which implements this, care to take a look @andrewrjones?
