### ISSUE TITLE
Style Enforcement

### ISSUE THREAD

**Issue by DarinJ** [mesos/hadoop#58]
Currently there is no style enforcement except by committers after a PR.  This is inefficient for everyone.  The maven check-styles plugin can help with this.  I was thinking of something pretty lax to start just watching for white space and unused imports.  Thoughts?

I'm happy to work this but this is a thorny issue, so I'd like committer feedback first.

**Comment by tarnfeld** [comment]
I'm +1 on the idea, whitespace and unused imports would be great as I think that's one of the biggest things that can make code feel inconsistent and a little annoying when reading.

Ping @brndnmtthws if you have any specific suggestions/objections to style enforcement?

It'd be great if you're willing to work on this @DarinJ! I'm happy to see it through to getting merged.

**Comment by brndnmtthws** [comment]
:+1: to enabling check style. I think we should stick to 2-spaces, and keep the formatting (mostly) the way it is.

**Comment by tarnfeld** [comment]
Awesome! We'll await your PR @DarinJ :smile:

**Comment by DarinJ** [comment]
Good news got this working, it did find a few infractions which I should fix before a PR (some bad white space and redundant imports mostly).  I really won't want to rebase after that refactor though, can we coordinate a bit?

**Comment by tarnfeld** [comment]
Yeah, I won't merge anything until this goes in.

**Comment by tarnfeld** [comment]
Fixed in #62!
