### ISSUE TITLE
Maven cannot build package

### ISSUE THREAD

**Issue by WiensCarson** [mesos/hadoop#64]
Hello!
I am using Maven 3.3.3, and when I followed the first few instructions in the README, I got this result:

me@server# mvn package

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mesos-hadoop-mr1 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.926 s
[INFO] Finished at: 2015-08-05T12:34:48-06:00
[INFO] Final Memory: 12M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mesos-hadoop-mr1: Could not resolve dependencies for project com.github.mesos:mesos-hadoop-mr1:jar:0.1.1-SNAPSHOT: Failed to collect dependencies at org.clojars.brenden:metrics-cassandra:jar:3.1.0: Failed to read artifact descriptor for org.clojars.brenden:metrics-cassandra:jar:3.1.0: Could not transfer artifact org.clojars.brenden:metrics-cassandra:pom:3.1.0 from/to clojars.org (http://clojars.org/repo): Access denied to: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.pom , ReasonPhrase:Forbidden. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

My machine is behind a proxy, but the proxy settings are correctly configured, and Maven is able to download other dependencies. This one in particular fails, even though I can access it in lynx, and download the pom in the URL using wget.

**Comment by tarnfeld** [comment]
Hmm. I've just attempted the same with a clean build environment and had no issue...

```
Downloading: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.pom
Downloaded: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.pom (2 KB at 5.1 KB/sec)
Downloading: https://repository.cloudera.com/artifactory/cloudera-repos/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.jar
Downloading: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.jar
Downloaded: http://clojars.org/repo/org/clojars/brenden/metrics-cassandra/3.1.0/metrics-cassandra-3.1.0.jar (12 KB at 63.9 KB/sec)
```

I'm not particularly sure what to suggest... maybe you got it sorted already?

**Comment by tarnfeld** [comment]
I'm going to close this for now, feel free to re-open if it's still an issue.
